--- #YAML:1.0
name:               UMLS-SenseRelate
version:            0.27
abstract:           ~
author:
    - Bridget McInnes <bthomson@umn.edu>, Ted Pedersen <tpederse@d.umn.edu>, Serguei Pakhomov <pakh0002@umn.edu>, Ying Liu <liux0395@umn.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Path:         2.08
    File::Spec:         3.31
    Statistics::TTest:  0.00
    UMLS::Interface:    1.09
    UMLS::Similarity:   1.05
    XML::Twig:          0.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
