---
abstract: unknown
author:
  - 'Bridget McInnes <bthomson@umn.edu>, Ted Pedersen <tpederse@d.umn.edu>, Serguei Pakhomov <pakh0002@umn.edu>, Ying Liu <liux0395@umn.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UMLS-SenseRelate
no_index:
  directory:
    - t
    - inc
requires:
  File::Path: 2.08
  File::Spec: 3.31
  UMLS::Interface: 1.09
  UMLS::Similarity: 1.05
  XML::Twig: 0
version: 0.17
