--- #YAML:1.0
name:               UMLS-SenseRelate
version:            0.01
abstract:           ~
author:
    - Bridget McInnes <bthomson@umn.edu>, Ted Pedersen <tpederse@d.umn.edu>, Serguei Pakhomov <pakh0002@umn.edu>, Ying Liu <liux0395@umn.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Path:        2.08
    File::Spec:        3.31
    UMLS::Interface:   0.89
    UMLS::Similarity:  0.89
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
